@isTest
private class DemoApexTop_TestClass {
	  static testMethod void doDev541_mod1_sample_test() { 
	  	
	  	DemoApexTop top = new DemoApexTop();
	  	PageReference ref = top.doDev541_mod1_sample();
	  }
	  
	  static testMethod void getDev541_mod1_governor_test() { 
	  	DemoApexTop top = new DemoApexTop();
	  	ID ref = top.getDev541_mod1_governor();
	  }
	  
	  static testMethod void doDev541_mod1_withsharing_test() { 
	  	DemoApexTop top = new DemoApexTop();
	  	PageReference ref = top.doDev541_mod1_withsharing();
	  }
	 
	  static testMethod void getDev541_mod1_withsharing_test() { 
	  	DemoApexTop top = new DemoApexTop();
	  	ID ref = top.getDev541_mod1_withsharing();
	  } 
	  	  
	  static testMethod void doDev541_mod3_DataType_test() { 
	  	DemoApexTop top = new DemoApexTop();
	  	PageReference ref = top.doDev541_mod3_DataType();
	  } 
	  
	  static testMethod void getDev541_mod3_DataType_test() { 
	  	DemoApexTop top = new DemoApexTop();
	  	ID ref = top.getDev541_mod3_DataType();
	  } 
	  
	  static testMethod void doDev541_mod3_sobject_test() { 
	  	DemoApexTop top = new DemoApexTop();
	  	PageReference ref = top.doDev541_mod3_sobject();
	  } 
	  
	  static testMethod void getDev541_mod3_sobject_test() { 
	  	DemoApexTop top = new DemoApexTop();
	  	ID ref = top.getDev541_mod3_sobject();
	  }
	  
	  static testMethod void doDev541_mod3_collection_test() { 
	  	DemoApexTop top = new DemoApexTop();
	  	PageReference ref = top.doDev541_mod3_collection();
	  } 
	  
	  static testMethod void getDev541_mod3_collection_test() { 
	  	DemoApexTop top = new DemoApexTop();
	  	String ref = top.getDev541_mod3_collection();
	  } 
	  
	  static testMethod void doDev541_mod3_query_test() { 
	  	DemoApexTop top = new DemoApexTop();
	  	PageReference ref = top.doDev541_mod3_query();
	  } 
	  
	  static testMethod void getDev541_mod3_query_test() { 
	  	DemoApexTop top = new DemoApexTop();
	  	String ref = top.getDev541_mod3_query();
	  } 
	  
	  static testMethod void doDev541_mod4_aggregatequery_test() { 
	  	DemoApexTop top = new DemoApexTop();
	  	PageReference ref = top.doDev541_mod4_aggregatequery();
	  } 
	  
	  static testMethod void getDev541_mod4_aggregatequery_test() { 
	  	DemoApexTop top = new DemoApexTop();
	  	String ref = top.getDev541_mod4_aggregatequery();
	  } 
	  
	  static testMethod void doDev541_mod4_sharing_test() { 
	  	DemoApexTop top = new DemoApexTop();
	  	PageReference ref = top.doDev541_mod4_sharing();
	  }
	  
	  static testMethod void getDev541_mod4_sharing_test() { 
	  	DemoApexTop top = new DemoApexTop();
	  	String ref = top.getDev541_mod4_sharing();
	  }  
	   static testMethod void doDev541_mod5_classlib_test() { 
	  	DemoApexTop top = new DemoApexTop();
	  	PageReference ref = top.doDev541_mod5_classlib();
	  }
	  static testMethod void getDev541_mod5_classlib_test() { 
	  	DemoApexTop top = new DemoApexTop();
	  	String ref = top.getDev541_mod5_classlib();
	  }
	  static testMethod void doDev541_mod6_trigger_test() { 
	  	DemoApexTop top = new DemoApexTop();
	  	PageReference ref = top.doDev541_mod6_trigger();
	  }
	  static testMethod void getDev541_mod6_trigger_test() { 
	  	DemoApexTop top = new DemoApexTop();
	  	String ref = top.getDev541_mod6_trigger();
	  }
	  
	  static testMethod void getDev541_mod7_testmethod_test() { 
	  	DemoApexTop top = new DemoApexTop();
	  	String ref = top.getDev541_mod7_testmethod();
	  }
	  
	  static testMethod void getDev541_mod9_HelloService_test() { 
	  	DemoApexTop top = new DemoApexTop();
	  	String ref = top.getDev541_mod9_HelloService();
	  }
	  
	  static testMethod void getDev541_mod9_Rest_test() { 
	  	DemoApexTop top = new DemoApexTop();
	  	String ref = top.getDev541_mod9_Rest();
	  }
	  
	  static testMethod void doDev541_mod9_Rest_test() { 
	  	DemoApexTop top = new DemoApexTop();
	  	PageReference ref = top.doDev541_mod9_Rest();
	  }
	  static testMethod void getDev541_mod10_mail_test() { 
	  	DemoApexTop top = new DemoApexTop();
	  	String ref = top.getDev541_mod10_mail();
	  }
	  
	  static testMethod void getDev541_mod11_describe_test() { 
	  	DemoApexTop top = new DemoApexTop();
	  	String ref = top.getDev541_mod11_describe();
	  }
	  
	  static testMethod void doDev541_mod11_describe_test() { 
	  	DemoApexTop top = new DemoApexTop();
	  	PageReference ref = top.doDev541_mod11_describe();
	  }
	  
	  static testMethod void getDev541_mod11_dynamicquery_test() { 
	  	DemoApexTop top = new DemoApexTop();
	  	String ref = top.getDev541_mod11_dynamicquery();
	  }
	  
	  static testMethod void doDev541_mod11_dynamicquery_test() { 
	  	DemoApexTop top = new DemoApexTop();
	  	PageReference ref = top.doDev541_mod11_dynamicquery();
	  }
	  
	  static testMethod void getDev541_mod11_dynamicDML_test() { 
	  	DemoApexTop top = new DemoApexTop();
	  	String ref = top.getDev541_mod11_dynamicDML();
	  }
	  
	  static testMethod void doDev541_mod11_dynamicDML_test() { 
	  	DemoApexTop top = new DemoApexTop();
	  	PageReference ref = top.doDev541_mod11_dynamicDML();
	  }
	  
	  static testMethod void getDev541_batchapex_test() { 
	  	DemoApexTop top = new DemoApexTop();
	  	String ref = top.getDev541_batchapex();
	  }
	  
	  static testMethod void doDev541_batchapex_test() { 
	  	DemoApexTop top = new DemoApexTop();
	  	PageReference ref = top.doDev541_batchapex();
	  }
	  
	  static testMethod void Dev541_mod11_describe_test() { 
	  	Dev541_mod11_describe top = new Dev541_mod11_describe();
	  	Dev541_mod11_describe.DescribeDemo();
	  }
	  
	 // static testMethod void getDev541_batchschedule_test() { 
	  //	DemoApexTop top = new DemoApexTop();
	 // 	String ref = top.getDev541_batchschedule();
	 // }
	  
	 // static testMethod void doDev541_batchschedule_test() { 
	  //	DemoApexTop top = new DemoApexTop();
	  //PageReference ref = top.doDev541_batchschedule();
	  //}
	  
}